name: Deploy Glue Job Scripts

on:
  push:
    branches: [ master ]

jobs:
  deploy-scripts:
    name: Upload Glue scripts to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload Glue job scripts to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp scripts/job_scrape_html.py s3://headlinesjune/scripts/job_scrape_html.py
          aws s3 cp scripts/job_process_html.py s3://headlinesjune/scripts/job_process_html.py
          aws s3 cp scripts/job_run_crawler.py s3://headlinesjune/scripts/job_run_crawler.py

